# Generated by Django 4.2.20 on 2025-03-18 17:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('color_code', models.CharField(default='primary', help_text='اسم اللون في Bootstrap مثل: primary, success, danger', max_length=20, verbose_name='كود اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف المورد',
                'verbose_name_plural': 'تصنيفات الموردين',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'مورد', 'verbose_name_plural': 'الموردين'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='debt',
        ),
        migrations.AddField(
            model_name='supplier',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف بديل'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المستحقات'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حد الائتمان'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_preferred',
            field=models.BooleanField(default=False, verbose_name='مورد مفضل'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ آخر شراء'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شروط الدفع'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('blocked', 'محظور')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المشتريات'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المورد'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="يجب أن يكون رقم الهاتف بتنسيق: '+999999999'. يُسمح بـ 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='suppliers.suppliercategory', verbose_name='التصنيف'),
        ),
    ]
