# ...existing code...
from customers import views as customer_views

urlpatterns = [
    # ...existing code...
    path('customers/categories/', customer_views.category_list, name='customer-categories'),
    # ...existing code...
]
