# Generated by Django 4.2.20 on 2025-03-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'سجل النشاط', 'verbose_name_plural': 'سجلات النشاط'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='model',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('import', 'استيراد'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع النشاط'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='description',
            field=models.TextField(default=0, verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الموديل'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='متصفح المستخدم'),
        ),
        migrations.AddField(
            model_name='user',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز اللون'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التوقيت'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('value_type', models.CharField(choices=[('str', 'نص'), ('int', 'عدد صحيح'), ('float', 'عدد عشري'), ('bool', 'قيمة منطقية'), ('json', 'JSON')], max_length=20, verbose_name='نوع القيمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='الفئة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم التحديث بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('text', models.TextField(verbose_name='النص')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تحذير'), ('danger', 'خطر')], default='info', max_length=20, verbose_name='نوع الإشعار')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
