# Generated by Django 4.2.20 on 2025-03-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
