# Generated by Django 4.2.20 on 2025-03-18 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_model_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل', 'verbose_name_plural': 'العملاء'},
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_name_f018e2_idx',
            old_name='customer_name_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_phone_8493fa_idx',
            old_name='customer_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_status_ce44cf_idx',
            old_name='customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_categor_e6e67b_idx',
            old_name='customer_category_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_debt_40a8e9_idx',
            old_name='customer_debt_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المديونية'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="يجب أن يكون رقم الهاتف بتنسيق: '+999999999'. يُسمح بـ 15 رقم.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
