# Generated by Django 4.2.20 on 2025-03-19 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color_code', models.CharField(choices=[('primary', 'أزرق'), ('secondary', 'رمادي'), ('success', 'أخضر'), ('danger', 'أحمر'), ('warning', 'برتقالي'), ('info', 'سماوي'), ('dark', 'أسود')], default='primary', max_length=20, verbose_name='كود اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف منتج',
                'verbose_name_plural': 'تصنيفات المنتجات',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_code',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الباركود'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الشراء'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=5, verbose_name='الحد الأدنى للمخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية في المخزون'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_name',
            field=models.CharField(choices=[('piece', 'قطعة'), ('kg', 'كيلوجرام'), ('liter', 'لتر'), ('meter', 'متر'), ('box', 'صندوق'), ('pack', 'عبوة'), ('set', 'طقم')], default='piece', max_length=20, verbose_name='وحدة القياس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('out_of_stock', 'نفذت الكمية')], default='active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_quantity', models.PositiveIntegerField(verbose_name='الكمية القديمة')),
                ('new_quantity', models.PositiveIntegerField(verbose_name='الكمية الجديدة')),
                ('change', models.IntegerField(verbose_name='التغيير')),
                ('adjustment_type', models.CharField(choices=[('add', 'إضافة'), ('subtract', 'خصم'), ('set', 'تعيين')], max_length=20, verbose_name='نوع التعديل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('adjustment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التعديل')),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'تعديل مخزون',
                'verbose_name_plural': 'تعديلات المخزون',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='التصنيف'),
        ),
    ]
